#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'Pushbuttons', class 'altera_avalon_pio'
 * The macros are prefixed with 'PUSHBUTTONS_'.
 * The prefix is the slave descriptor.
 */
#define PUSHBUTTONS_COMPONENT_TYPE altera_avalon_pio
#define PUSHBUTTONS_COMPONENT_NAME Pushbuttons
#define PUSHBUTTONS_BASE 0x0
#define PUSHBUTTONS_SPAN 16
#define PUSHBUTTONS_END 0xf
#define PUSHBUTTONS_IRQ 1
#define PUSHBUTTONS_BIT_CLEARING_EDGE_REGISTER 1
#define PUSHBUTTONS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PUSHBUTTONS_CAPTURE 1
#define PUSHBUTTONS_DATA_WIDTH 4
#define PUSHBUTTONS_DO_TEST_BENCH_WIRING 1
#define PUSHBUTTONS_DRIVEN_SIM_VALUE 0
#define PUSHBUTTONS_EDGE_TYPE FALLING
#define PUSHBUTTONS_FREQ 48000000
#define PUSHBUTTONS_HAS_IN 1
#define PUSHBUTTONS_HAS_OUT 0
#define PUSHBUTTONS_HAS_TRI 0
#define PUSHBUTTONS_IRQ_TYPE EDGE
#define PUSHBUTTONS_RESET_VALUE 0

/*
 * Macros for device 'mic_system_0', class 'mic_system'
 * The macros are prefixed with 'MIC_SYSTEM_0_'.
 * The prefix is the slave descriptor.
 */
#define MIC_SYSTEM_0_COMPONENT_TYPE mic_system
#define MIC_SYSTEM_0_COMPONENT_NAME mic_system_0
#define MIC_SYSTEM_0_BASE 0x10
#define MIC_SYSTEM_0_SPAN 16
#define MIC_SYSTEM_0_END 0x1f

/*
 * Macros for device 'mic_system_2_0', class 'mic_system_2'
 * The macros are prefixed with 'MIC_SYSTEM_2_0_'.
 * The prefix is the slave descriptor.
 */
#define MIC_SYSTEM_2_0_COMPONENT_TYPE mic_system_2
#define MIC_SYSTEM_2_0_COMPONENT_NAME mic_system_2_0
#define MIC_SYSTEM_2_0_BASE 0x20
#define MIC_SYSTEM_2_0_SPAN 16
#define MIC_SYSTEM_2_0_END 0x2f


#endif /* _ALTERA_HPS_0_H_ */
